image: maven:latest
stages:
    - build
    - test
build_job_:
    stage: build
    tags:
    - docker
    script: 
        - "mvn compile"
test_job_:
    stage: test
    tags:
    - docker
    script: 
        - "mvn test"
